/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...404]': RouteRecordInfo<
      '/[...404]',
      '/:404(.*)',
      { 404: ParamValue<true> },
      { 404: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/about-angularjs-ng-if': RouteRecordInfo<
      '/posts/about-angularjs-ng-if',
      '/posts/about-angularjs-ng-if',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/blog-reborn': RouteRecordInfo<
      '/posts/blog-reborn',
      '/posts/blog-reborn',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/flex-layout': RouteRecordInfo<
      '/posts/flex-layout',
      '/posts/flex-layout',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/git-commands': RouteRecordInfo<
      '/posts/git-commands',
      '/posts/git-commands',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/learning-react-router-v7': RouteRecordInfo<
      '/posts/learning-react-router-v7',
      '/posts/learning-react-router-v7',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/my-first-monorepo': RouteRecordInfo<
      '/posts/my-first-monorepo',
      '/posts/my-first-monorepo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/my-first-npm-package': RouteRecordInfo<
      '/posts/my-first-npm-package',
      '/posts/my-first-npm-package',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/scoop-install-vscode': RouteRecordInfo<
      '/posts/scoop-install-vscode',
      '/posts/scoop-install-vscode',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/slice-vs-splice': RouteRecordInfo<
      '/posts/slice-vs-splice',
      '/posts/slice-vs-splice',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/technology-stack-big-zooming': RouteRecordInfo<
      '/posts/technology-stack-big-zooming',
      '/posts/technology-stack-big-zooming',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'pages/index.md': {
      routes:
        | '/'
      views:
        | never
    }
    'pages/[...404].md': {
      routes:
        | '/[...404]'
      views:
        | never
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
    }
    'pages/posts/index.md': {
      routes:
        | '/posts/'
      views:
        | never
    }
    'pages/posts/about-angularjs-ng-if.md': {
      routes:
        | '/posts/about-angularjs-ng-if'
      views:
        | never
    }
    'pages/posts/blog-reborn.md': {
      routes:
        | '/posts/blog-reborn'
      views:
        | never
    }
    'pages/posts/flex-layout.md': {
      routes:
        | '/posts/flex-layout'
      views:
        | never
    }
    'pages/posts/git-commands.md': {
      routes:
        | '/posts/git-commands'
      views:
        | never
    }
    'pages/posts/learning-react-router-v7.md': {
      routes:
        | '/posts/learning-react-router-v7'
      views:
        | never
    }
    'pages/posts/my-first-monorepo.md': {
      routes:
        | '/posts/my-first-monorepo'
      views:
        | never
    }
    'pages/posts/my-first-npm-package.md': {
      routes:
        | '/posts/my-first-npm-package'
      views:
        | never
    }
    'pages/posts/scoop-install-vscode.md': {
      routes:
        | '/posts/scoop-install-vscode'
      views:
        | never
    }
    'pages/posts/slice-vs-splice.md': {
      routes:
        | '/posts/slice-vs-splice'
      views:
        | never
    }
    'pages/posts/technology-stack-big-zooming.md': {
      routes:
        | '/posts/technology-stack-big-zooming'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
